In [1]:
import numpy
array=numpy.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [2]:
import numpy
array=numpy.array([10,20,30,40,50])
print(type(array))

<class 'numpy.ndarray'>


In [4]:
import numpy
array=numpy.array([10,20,30,40,50])
print(array[1])

20


In [5]:
import numpy
array=numpy.array([10,20,30,40,50])
print(array[1]+array[2])

50


In [9]:
import numpy
array=numpy.array([10,20,30,40,50])
print(array[0:5:2])

[10 30 50]


In [11]:
import numpy
array=numpy.array([10,20,30,40,50])
print(array[-5:])

[10 20 30 40 50]


In [13]:
import numpy as np
array=np.array([10,20,30,40,50])
array1=array.copy()
print(array1)

[10 20 30 40 50]


In [17]:
import numpy as np
array=np.array([10,20,30,40,50])
for i in array:
    print(i,end=",")

10,20,30,40,50,

In [19]:
import numpy as np
array=np.array([10,20,30,40,50])
array1=np.array([20,30,40,50,60])
print(array+array1)

[ 30  50  70  90 110]


In [22]:
import numpy as np
array=np.array([10,20,30,40,50])
array1=np.array([20,30,40,50,60])
array3=np.concatenate((array,array1))
print(array3)

[10 20 30 40 50 20 30 40 50 60]


In [23]:
import numpy as np
array=np.array([10,20,30,40,50])
array1=np.array_split(array,4)
print(array1)

[array([10, 20]), array([30]), array([40]), array([50])]


In [24]:
import numpy as np
array=np.array([40,20,60,40,50])
array1=np.sort(array)
print(array1)

[20 40 40 50 60]


In [25]:
import numpy as np
array=np.array([40,20,60,40,50])
array1=[True,False,True,False,True]
array2=array[array1]
print(array2)

[40 60 50]


In [32]:
from numpy import random
value=random.randint(100)
print(value)

84


In [37]:
from numpy import random
value=random.rand()
print(value)

0.32344177852508693


In [40]:
from numpy import random
value=random.choice([10,20,30,40,50])
print(value)

40


In [41]:
import numpy
array=numpy.array(42)
print(array)

42


In [42]:
import numpy
array=numpy.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [43]:
import numpy
array=numpy.array([[1,2,3,4,5],[2,3,4,5,6]])
print(array)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [44]:
import numpy
array=numpy.array([[1,2,3,4,5],[2,3,4,5,6]])
print(array[1][4])

6
